### ISSUE TITLE
Error when trying to build the iOS example

### ISSUE THREAD

**Issue by narner** [AVUIs/ofxAVUI#9]
When building the iOS example app, I get the error shown in the screen-shot below:

![screen shot 2016-07-16 at 5 24 05 pm](https://cloud.githubusercontent.com/assets/2131591/16901079/add27a70-4c06-11e6-9376-a858e1a0417f.png)

**Comment by nunocorreia** [comment]
It seems you are trying to build it in the OS X version of openFrameworks, not the iOS version. Please place the add-on in the addons folder of openFrameworks for iOS version, which you can download here http://openframeworks.cc/download/
